### ISSUE TITLE
ImportError: No module named ijson

### ISSUE THREAD

**Issue by chezdrz** [firebase/firebase-streaming-import#10]
On running the import I get the following error 

Traceback (most recent call last):
  File "import.py", line 1, in <module>
    import ijson
ImportError: No module named ijson
---
Note: During the install I did get the following error as well 
$ pip install -r requirements.txt
Collecting requests (from -r requirements.txt (line 1))
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 875kB/s 
Collecting argparse (from -r requirements.txt (line 2))
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Collecting ijson (from -r requirements.txt (line 3))
  Downloading ijson-2.3-py2.py3-none-any.whl
Collecting traceback (from -r requirements.txt (line 4))
  Could not find a version that satisfies the requirement traceback (from -r requirements.txt (line 4)) (from versions: )
No matching distribution found for traceback (from -r requirements.txt (line 4))

>> I removed the traceback line and tried a re-install and then get the 2nd error
Installing collected packages: certifi, chardet, idna, urllib3, requests, argparse, ijson
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/certifi-2017.11.5.dist-info'

**Comment by chezdrz** [comment]
Please ignore the 2nd error, I have resolved that , it was due to a permissions issue.
